version: "2"

networks: 
  test:
    

services: 
  reporting-org1:
    build:
      context: ../minor
      dockerfile: Dockerfile
    env_file: .env
    ports: 
      - "3000:3000"
    container_name: reporting-org1
    networks: 
      - test        
